[theme]
base = "dark"
primaryColor = "#F5A623"
backgroundColor = "#080D12"
secondaryBackgroundColor = "#0E151D"
textColor = "#F1F5F9"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
