[theme]
base = "light"
primaryColor = "#59CE2A"
backgroundColor = "#F4F5F3"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17201D"
font = "sans serif"

[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
